<a href="https://colab.research.google.com/github/abdulhamidll/Data-Science/blob/main/import_sqlite3_as_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import sqlite3 as sql
from pprint import pprint as print

In [16]:
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

--2022-05-17 11:16:55--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 151.139.128.11
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|151.139.128.11|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.1s

2022-05-17 11:16:56 (2.81 MB/s) - ‘chinook.zip’ saved [305596/305596]

In [17]:
!unzip chinook.zip

Archive:  chinook.zip
replace chinook.db? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: chinook.db

In [18]:
db = sql.connect("chinook.db")
cursor = db.cursor()

In [21]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())
# komanda = "SELECT CustomerId, Firstname, LastName, Phone, Country FROM customers"
# df = pd.read_sql(komanda, db, index_col="CustomerId")
# df

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [25]:
query = "SELECT FirstName, LastName, City, State, Phone, Email FROM customers ORDER BY FirstName"
pd.read_sql(query, db)

,FirstName,LastName,City,State,Phone,Email
0,Aaron,Mitchell,Winnipeg,MB,+1 (204) 452-6452,aaronmitchell@yahoo.ca
1,Alexandre,Rocha,São Paulo,SP,+55 (11) 3055-3278,alero@uol.com.br
2,Astrid,Gruber,Vienne,None,+43 01 5134505,astrid.gruber@apple.at
3,Bjørn,Hansen,Oslo,None,+47 22 44 22 22,bjorn.hansen@yahoo.no
4,Camille,Bernard,Paris,None,+33 01 49 70 65 65,camille.bernard@yahoo.fr
5,Daan,Peeters,Brussels,None,+32 02 219 03 03,daan_peeters@apple.be
6,Dan,Miller,Mountain View,CA,+1 (650) 644-3358,dmiller@comcast.com
7,Diego,Gutiérrez,Buenos Aires,None,+54 (0)11 4311 4333,diego.gutierrez@yahoo.ar
8,Dominique,Lefebvre,Paris,None,+33 01 47 42 71 71,dominiquelefebvre@gmail.com
9,Eduardo,Martins,São Paulo,SP,+55 (11) 3033-5446,eduardo@woodstock.com.br
10,Edward,Francis,Ottawa,ON,+1 (613) 234-3322,edfrancis@yachoo.ca
11,Ellie,Sullivan,Yellowknife,NT,+1 (867) 920-2233,ellie.sullivan@shaw.ca
12,Emma,Jones,London,None,+44 020 7707 0707,emma_jones@hotmail.com
13,Enrique,Muñoz,Madrid,None,+34 914 454 454,enrique_munoz@yahoo.es
14,Fernanda,Ramos,Brasília,DF,+55 (61) 3363-5547,fernadaramos4@uol.com.br
15,Frank,Harris,Mountain View,CA,+1 (650) 253-0000,fharris@google.com
16,Frank,Ralston,Chicago,IL,+1 (312) 332-3232,fralston@gmail.com
17,František,Wichterlová,Prague,None,+420 2 4172 5555,frantisekw@jetbrains.com
18,François,Tremblay,Montréal,QC,+1 (514) 721-4711,ftremblay@gmail.com
19,Fynn,Zimmermann,Frankfurt,None,+49 069 40598889,fzimmermann@yahoo.de
20,Hannah,Schneider,Berlin,None,+49 030 26550280,hannah.schneider@yahoo.de
21,Heather,Leacock,Orlando,FL,+1 (407) 999-7788,hleacock@gmail.com
22,Helena,Holý,Prague,None,+420 2 4177 0449,hholy@gmail.com
23,Hugh,O'Reilly,Dublin,Dublin,+353 01 6792424,hughoreilly@apple.ie
24,Isabelle,Mercier,Dijon,None,+33 03 80 73 66 99,isabelle_mercier@apple.fr
25,Jack,Smith,Redmond,WA,+1 (425) 882-8080,jacksmith@microsoft.com
26,Jennifer,Peterson,Vancouver,BC,+1 (604) 688-2255,jenniferp@rogers.ca
27,Joakim,Johansson,Stockholm,None,+46 08-651 52 52,joakim.johansson@yahoo.se
28,Johannes,Van der Berg,Amsterdam,VV,+31 020 6223130,johavanderberg@yahoo.nl
29,John,Gordon,Boston,MA,+1 (617) 522-1333,johngordon22@yahoo.com
30,João,Fernandes,Lisbon,None,+351 (213) 466-111,jfernandes@yahoo.pt
31,Julia,Barnett,Salt Lake City,UT,+1 (801) 531-7272,jubarnett@gmail.com
32,Kara,Nielsen,Copenhagen,None,+453 3331 9991,kara.nielsen@jubii.dk
33,Kathy,Chase,Reno,NV,+1 (775) 223-7665,kachase@hotmail.com
34,Ladislav,Kovács,Budapest,None,None,ladislav_kovacs@apple.hu
35,Leonie,Köhler,Stuttgart,None,+49 0711 2842222,leonekohler@surfeu.de
36,Lucas,Mancini,Rome,RM,+39 06 39733434,lucas.mancini@yahoo.it
37,Luis,Rojas,Santiago,None,+56 (0)2 635 4444,luisrojas@yahoo.cl
38,Luís,Gonçalves,São José dos Campos,SP,+55 (12) 3923-5555,luisg@embraer.com.br
39,Madalena,Sampaio,Porto,None,+351 (225) 022-448,masampaio@sapo.pt
40,Manoj,Pareek,Delhi,None,+91 0124 39883988,manoj.pareek@rediff.com
41,Marc,Dubois,Lyon,None,+33 04 78 30 30 30,marc.dubois@hotmail.com
42,Mark,Philips,Edmonton,AB,+1 (780) 434-4554,mphilips12@shaw.ca
43,Mark,Taylor,Sidney,NSW,+61 (02) 9332 3633,mark.taylor@yahoo.au
44,Martha,Silk,Halifax,NS,+1 (902) 450-0450,marthasilk@gmail.com
45,Michelle,Brooks,New York,NY,+1 (212) 221-3546,michelleb@aol.com
46,Niklas,Schröder,Berlin,None,+49 030 2141444,nschroder@surfeu.de
47,Patrick,Gray,Tucson,AZ,+1 (520) 622-4200,patrick.gray@aol.com
48,Phil,Hughes,London,None,+44 020 7976 5722,phil.hughes@gmail.com
49,Puja,Srivastava,Bangalore,None,+91 080 22289999,puja_srivastava@yahoo.in
50,Richard,Cunningham,Fort Worth,TX,+1 (817) 924-7272,ricunningham@hotmail.com
51,Robert,Brown,Toronto,ON,+1 (416) 363-8888,robbrown@shaw.ca
52,Roberto,Almeida,Rio de Janeiro,RJ,+55 (21) 2271-7000,roberto.almeida@riotur.gov.br
53,Stanisław,Wójcik,Warsaw,None,+48 22 828 37 39,stanisław.wójcik@wp.pl
54,Steve,Murray,Edinburgh,None,+44 0131 315 3300,steve.murray@yahoo.uk
55,Terhi,Hämäläinen,Helsinki,None,+358 09 870 2000,terhi.hamalainen@apple.fi
56,Tim,Goyer,Cupertino,CA,+1 (408) 996-1010,tgoyer@apple.com
57,Victor,Stevens,Madison,WI,+1 (608) 257-0597,vstevens@yahoo.com
58,Wyatt,Girard,Bordeaux,None,+33 05 56 96 96 96,wyatt.girard@yahoo.fr

In [27]:
query = "SELECT DISTINCT Country FROM customers"
cursor.execute(query)
cursor.fetchall()

[('Brazil',),
 ('Germany',),
 ('Canada',),
 ('Norway',),
 ('Czech Republic',),
 ('Austria',),
 ('Belgium',),
 ('Denmark',),
 ('USA',),
 ('Portugal',),
 ('France',),
 ('Finland',),
 ('Hungary',),
 ('Ireland',),
 ('Italy',),
 ('Netherlands',),
 ('Poland',),
 ('Spain',),
 ('Sweden',),
 ('United Kingdom',),
 ('Australia',),
 ('Argentina',),
 ('Chile',),
 ('India',)]